version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: domain_nest
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      MYSQL_HOST: db
      MYSQL_DATABASE: domain_nest
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
